# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 122900f38ffaaa5b9186fc7734c427628dd8c22c34a0ef29b0f5f2aad083f5e88a589182bed7c5d5468ae8ff7789499147ecab5018dac82d12a998922e962132

test:
  secret_key_base: e56eaa300e3f480145ca250223a7392c6e5a730f59716197bcbad64265d237cd319f2154745cf5211106a983d414a67e6c018c733629b681ec1f5bbd366cc66f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
